/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ibm.able;

import org.junit.Test;
import static org.junit.Assert.*;

public class AccessibilityCheckerTest {
    @Test public void someLibraryMethodReturnsTrue() {
        AccessibilityChecker classUnderTest = new AccessibilityChecker();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
