/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ibm.able;

public class AccessibilityChecker {
    public boolean someLibraryMethod() {
        return true;
    }
}
